### ISSUE TITLE
Publish 0.1.3?

### ISSUE THREAD

**Issue by AndreasBackx** [gocardless/gocardless-pro-python#1]
[The commits since 0.1.2](https://github.com/gocardless/gocardless-pro-python/compare/v0.1.2...master) are backwards compatible and the resource changes since represent the current API. It would be great if the changes were published so that they can be used without installing directly from the repo with pip.

**Comment by jbouzekri** [comment]
+1.

For example, redirect_flows in 0.1.2 does not expose customer_bank_account in links.

**Comment by greysteil** [comment]
Thanks for the heads up guys. @hmarr - can you make it so?

**Comment by hmarr** [comment]
Just pushed v0.2.0 to PyPI.
