### ISSUE TITLE
Broken home page link un pypi package

### ISSUE THREAD

**Issue by blatinier** [gocardless/gocardless-pro-python#10]
Pypi package defines the homepage of the project to https://gocardless.com/docs/python/merchant_client_guide which leads to a 404 for me.

**Comment by timrogers** [comment]
Ah, that's out of date! I'll change it once I've got access and can upload the updated package ✅

**Comment by timrogers** [comment]
@blatinier Can you show me where this link is? I can't track it down.

**Comment by blatinier** [comment]
At the bottom of this page: https://pypi.python.org/pypi/gocardless/0.5.3
This is meta information on the package you distribute to pypi. You update it using twine or by uploading a PKG-INFO file to pypi. Go to the pypi interface, it's explained there.

**Comment by timrogers** [comment]
That's for our [Legacy API](https://developer.gocardless.com/legacy) - the library in this repo for our current API is at https://pypi.python.org/pypi/gocardless_pro. I'll look at getting that link changed.

**Comment by blatinier** [comment]
If it's legacy you should add some big warnings about that too I think.

**Comment by timrogers** [comment]
Done! Thanks for your suggestion :heart:
