### ISSUE TITLE
tests directory should be part of the gocardless_pro package

### ISSUE THREAD

**Issue by mapleoin** [gocardless/gocardless-pro-python#2]
Right now the `tests` directory gets installed as a top-level python package i.e. under `python/site-packages/`. 

Tests should either be under `python/site-packages/gocardless_pro` or not be in the python package at all.

**Comment by hmarr** [comment]
Eek, that's horrible - thanks for pointing that out!

[This change](https://github.com/gocardless/gocardless-pro-python/commit/99849d87f0653a500de58f5e7fe891b5b0202827#diff-2eeaed663bd0d25b7e608891384b7298L9) seems to fix the issue. I've just pushed v0.2.1, which includes this commit. Let me know if that doesn't do the job.
