### ISSUE TITLE
ValidationFailedError: <unprintable ValidationFailedError object> on duplicate bank_account 

### ISSUE THREAD

**Issue by mapleoin** [gocardless/gocardless-pro-python#4]
Trying to create the same bank account twice with `client.customer_bank_accounts.create` raises an unprintable ValidationFailedError:

```
        error = response.json()['error']
        exception_class = errors.ApiError.exception_for(error['type'])
>       raise exception_class(error)
E       ValidationFailedError: <unprintable ValidationFailedError object>
```

Looking at `errors.py` it seems that it wants to format a `field` key in `__str__` which is not returned by the API. The actual error JSON object is:

```
{u'reason': u'bank_account_exists', u'message': u'Bank account already exists', u'links': {u'customer_bank_account': u'BA0000G3T3J8XC'}}
```

**Comment by hmarr** [comment]
Thanks for reporting, and apologies for the delay. This has been fixed in v0.2.2.
