### ISSUE TITLE
Malformed response when deleting a customer

### ISSUE THREAD

**Issue by macukadam** [gocardless/gocardless-pro-python#63]
I am using pip gocardless-pro 1.31.0 release. Python version 3.10.0. 

The error occures when deleting a client. The client is succesfully deleted however the request then throws MalformedResponseError. I've also tried to use earlier pip versions, the result is the same. The client returns 204 which also indicates successful operation. For now I am just expecting MalformedResponseError on my tests. I am using gocardless sandbox environment for all my tests.

gocardless_pro/api_client.py
line 117: 
![image](https://user-images.githubusercontent.com/22873325/179722709-736abe1a-6215-4c02-b1ab-95383827abab.png)

Here is full test output:
![image](https://user-images.githubusercontent.com/22873325/179723357-a9918e83-1ca3-4aeb-b8c8-8adfda0b37cc.png)

**Comment by xlvisuals** [comment]
The bug still exists in v1.39.0

**Comment by 1dimir** [comment]
It seems that there should be an exception for HTTP 204 case. 

[Documentation](https://developer.gocardless.com/api-reference#customers-remove-a-customer) provides a sample successful response with no body. 

Here is fix: https://github.com/gocardless/gocardless-pro-python/pull/81

**Comment by hjheath** [comment]
This should be fixed in https://github.com/gocardless/gocardless-pro-python/releases/tag/v1.46.1
