### ISSUE TITLE
Any Plans to support the oauth flow?

### ISSUE THREAD

**Issue by brickcap** [gocardless/gocardless-pro-python#7]
Hi Everyone,

I was wondering if there are plans to integrate the [oauth flow](https://developer.gocardless.com/pro/2015-07-06/#guides-oauth) in the python library. 

Thanks,
Akshat

**Comment by hmarr** [comment]
Thanks for raising this, @brickcap. We have no current plans, but I'll make sure we consider it internally and update this issue if & when we decide to proceed to implementation.
