### ISSUE TITLE
code error resources.MandateRequestConstraints

### ISSUE THREAD

**Issue by blaggacao** [gocardless/gocardless-pro-python#84]
v1.45.0 is affcted.

https://github.com/gocardless/gocardless-pro-python/blob/62fbef3a116b8ce5ad5f174f212c10a54698107c/gocardless_pro/services/mandate_request_constraints_service.py#L16C51-L16C51

```
python3.10-gocardless-pro>     RESOURCE_CLASS = resources.MandateRequestConstraints
python3.10-gocardless-pro> AttributeError: module 'gocardless_pro.resources' has no attribute 'MandateRequestConstraints'
```

It is [effectively _not_ exported](https://github.com/gocardless/gocardless-pro-python/blob/master/gocardless_pro/resources/__init__.py). Seems like  `crank` didn't run or make a mistake.

**Comment by hjheath** [comment]
I've just removed this resource from the library in https://github.com/gocardless/gocardless-pro-python/pull/88

This resources was added mistakenly and crank did not remove it when we removed it. You can still specify and access the `mandate[request_constraints]` field on the billing request resource.
